### PR TITLE
 Update to v1.69.0_1, update recipe, rerender

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
Includes https://github.com/conda-forge/r-bh-feedstock/pull/6

**Comment by dbast** [comment]
Ready to merge. Thanks

**Comment by cbrueffer** [comment]
Maybe I haven't kept up with the news, is the maintainer change intentional?

**Comment by dbast** [comment]
@cbrueffer Yes, see https://github.com/bgruening/conda_r_skeleton_helper/blob/master/extra.yaml ... makes it easier to update ... @conda-forge/r is a group, where all the r maintainers are part of.

**Comment by dbast** [comment]
The mechanism which applies those changes to the repo is also supporting it.

**Comment by cbrueffer** [comment]
Cool, thanks for the info! Looks much more maintainable indeed.

**Pull request merged**
